---
apiVersion: v1
kind: Namespace
metadata:
  name: hello

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello
  namespace: hello
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: hello
  chart:
    git: git@github.com:jlott/k8s-config
    path: charts/hello
    ref: master
  values:
    image:
      repository: squareroot/hello
      tag: dev-vn8gelui
    replicaCount: 1
