---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: 'semver: *'
  name: hello
  namespace: hello
spec:
  values:
    image:
      tag: 0.0.1
    replicaCount: 2
