---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: 'semver: *'
  name: podinfo
  namespace: podinfo
spec:
  values:
    image:
      tag: 0.0.2
    replicaCount: 2
