---
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:jlott/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: justinlott/podinfo
      tag: dev-7yswaxr3
    replicaCount: 1
    hpa:
      enabled: false
